
#this method directly raise an exception that remains unsolved to the user

def third_method(base_num):
	raise Exception('An error hanppened when generating the class id!!!')